### ISSUE TITLE
进行预训练的时候报错。

### ISSUE THREAD

**Issue by musellama** [ymcui/Chinese-LLaMA-Alpaca-2#27]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Windows

### 详细描述问题

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 28969) of binary: 
提示报错了，查资料好像说是，版本问题
系统是windows wsl Ubuntu 20.04
Python 3.9.17
torch  2.0.1+cu117

### 依赖情况（代码类问题务必提供）

```
 pip list | grep -E 'transformers|peft|torch'
peft                     0.4.0
torch                    2.0.1
transformers             4.31.0
```

### 运行日志或截图

```
[INFO|trainer.py:1686] 2023-08-01 08:21:52,370 >> ***** Running training *****
[INFO|trainer.py:1687] 2023-08-01 08:21:52,370 >>   Num examples = 8,328
[INFO|trainer.py:1688] 2023-08-01 08:21:52,371 >>   Num Epochs = 1
[INFO|trainer.py:1689] 2023-08-01 08:21:52,371 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1692] 2023-08-01 08:21:52,371 >>   Total train batch size (w. parallel, distributed & accumulation) = 2
[INFO|trainer.py:1693] 2023-08-01 08:21:52,371 >>   Gradient Accumulation steps = 2
[INFO|trainer.py:1694] 2023-08-01 08:21:52,371 >>   Total optimization steps = 4,164
[INFO|trainer.py:1695] 2023-08-01 08:21:52,372 >>   Number of trainable parameters = 159,907,840
  0%|                                                                                          | 0/4164 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/maguoheng/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_pt_with_peft.py", line 636, in <module>
    main()
  File "/home/maguoheng/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_pt_with_peft.py", line 604, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1769, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 806, in forward
    outputs = self.model(
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 330, in forward
    attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)) / math.sqrt(self.head_dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 23.99 GiB total capacity; 22.70 GiB already allocated; 0 bytes free; 22.88 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|                                                                                          | 0/4164 [00:01<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 28969) of binary: /home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/bin/python
Traceback (most recent call last):
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
run_clm_pt_with_peft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-01_08:21:58
  host      : MICROSO-AR91S8Q.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 28969)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by musellama** [comment]
@ymcui 帮帮我，llama1的时候还好着

**Comment by iMountTai** [comment]
贴一下运行脚本，另外peft版本不是我们要求的版本`pip install git+https://github.com/huggingface/peft.git@13e53fc`

**Comment by musellama** [comment]
@ymcui 这个配置用的conda 环境 跑 llama-chinese-alpaca-1 是可以跑的。但是到2就不行了

**Comment by musellama** [comment]
@iMountTai 
 #--modules_to_save ${modules_to_save} \
 #--gradient_checkpointing \
lr=2e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=path/model/chinese-alpaca-2-7b-hf
chinese_tokenizer_path=path/tokenizer
dataset_dir=path/yuliao
data_cache=temp_data_cache_dir
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=2
output_dir=output_dir

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size 1024 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --ddp_find_unused_parameters False

**Comment by musellama** [comment]
pip list | grep -E 'transformers|peft|torch'
peft                     0.3.0.dev0
torch                    2.0.1
transformers             4.31.0
换到这个版本了 运行还是报错

**Comment by musellama** [comment]
pip install git+https://github.com/huggingface/peft.git@13e53fc 
在下载peft的时候 提示未找到？ 后边的地址不对 @13e53fc 
WARNING: Did not find branch or tag '13e53fc', assuming revision or ref.

**Comment by airaria** [comment]
coda out of memory了。
可能因为block_size比一代大的缘故。
你把block_size调到512试试。

**Comment by musellama** [comment]
> 
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=1
--block_size 512 \
这是显存显示
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 23.99 GiB total capacity; 22.70 GiB already allocated; 0 bytes free; 22.88 GiB reserved in total by PyTorch)

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19991) of binary: /home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/bin/python

还是报错，不是预训练数据的问题1可以训练

pip install git+https://github.com/huggingface/peft.git@13e53fc 下载提示 未找到 @13e53fc  不正确
python 3.9
cuda 117
peft                     0.3.0.dev0
torch                    2.0.1
transformers             4.31.0

**Comment by airaria** [comment]
> per_device_train_batch_size=1 per_device_eval_batch_size=1 gradient_accumulation_steps=1 --block_size 512 这是显存显示 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 23.99 GiB total capacity; 22.70 GiB already allocated; 0 bytes free; 22.88 GiB reserved in total by PyTorch)
> 
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19991) of binary: /home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/bin/python
> 
> 还是报错，不是预训练数据的问题1可以训练
> 
> pip install git+https://github.com/huggingface/peft.git@13e53fc 下载提示 未找到 @13e53fc 不正确 python 3.9 cuda 117 peft 0.3.0.dev0 torch 2.0.1 transformers 4.31.0

修改block_size删除旧cache了吗？不然还会读取之前的数据

**Comment by musellama** [comment]
pip install git+https://github.com/huggingface/peft.git@13e53fc7ee5d89d59b16523051006dddf0fb7a49
可以下载了

**Comment by musellama** [comment]
> > per_device_train_batch_size=1 per_device_eval_batch_size=1 gradient_accumulation_steps=1 --block_size 512 这是显存显示 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 23.99 GiB total capacity; 22.70 GiB already allocated; 0 bytes free; 22.88 GiB reserved in total by PyTorch)
> > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 19991) of binary: /home/maguoheng/anaconda3/envs/chinese-llama2-alpaca/bin/python
> > 还是报错，不是预训练数据的问题1可以训练
> > pip install git+https://github.com/huggingface/peft.git@13e53fc 下载提示 未找到 @13e53fc 不正确 python 3.9 cuda 117 peft 0.3.0.dev0 torch 2.0.1 transformers 4.31.0
> 
> 修改block_size后删除旧cache了吗？不然还会读取之前的数据

好的我试试重新弄

**Comment by musellama** [comment]
> cuda out of memory了。 可能因为block_size比一代大的缘故。 你把block_size调到512试试。

谢谢铁子 果然是 --block_size 的问题 把前边的删除了就OK了

**Comment by lx256** [comment]
我也遇到了类似的错误， 但是没有提示显存不足的问题，下面是报错日志，请大佬帮忙看下：
依赖版本：
peft                     0.3.0.dev0
torch                    2.0.1
transformers             4.31.0

08/01/2023 16:20:22 - INFO - __main__ - Num train_samples  5966
08/01/2023 16:20:22 - INFO - __main__ - training example:
08/01/2023 16:20:22 - INFO - __main__ - <s> [INST] <<SYS>>
You are a helpful assistant. 你是一个乐于助人的助手。
<</SYS>>

是这个连嘛 [/INST] 要使用密钥才能连接
我们测试服务器都是这个密钥</s>
Traceback (most recent call last):
  File "/home/cloudam/studio_ai/code/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py", line 435, in <module>
    main()
  File "/home/cloudam/studio_ai/code/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py", line 319, in main
    logger.info(f"Evaluation files: {' '.join(files)}")
TypeError: sequence item 0: expected str instance, NoneType found
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 21998) of binary: /home/cloudam/.conda/envs/chinese-llama2/bin/python
Traceback (most recent call last):
  File "/home/cloudam/.conda/envs/chinese-llama2/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
  File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by airaria** [comment]
@Crispy256 是不是没提供验证集`--validation_file`?

**Comment by Crispy256** [comment]
> 我也遇到了类似的错误， 但是没有提示显存不足的问题，下面是报错日志，请大佬帮忙看下： 依赖版本： peft 0.3.0.dev0 torch 2.0.1 transformers 4.31.0
> 
> 08/01/2023 16:20:22 - INFO - **main** - Num train_samples 5966 08/01/2023 16:20:22 - INFO - **main** - training example: 08/01/2023 16:20:22 - INFO - **main** - [INST] <> You are a helpful assistant. 你是一个乐于助人的助手。 <>
> 
> 是这个连嘛 [/INST] 要使用密钥才能连接 我们测试服务器都是这个密钥 Traceback (most recent call last): File "/home/cloudam/studio_ai/code/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py", line 435, in main() File "/home/cloudam/studio_ai/code/Chinese-LLaMA-Alpaca-2/scripts/training/run_clm_sft_with_peft.py", line 319, in main logger.info(f"Evaluation files: {' '.join(files)}") TypeError: sequence item 0: expected str instance, NoneType found ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 21998) of binary: /home/cloudam/.conda/envs/chinese-llama2/bin/python Traceback (most recent call last): File "/home/cloudam/.conda/envs/chinese-llama2/bin/torchrun", line 33, in sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')()) File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper return f(*args, **kwargs) File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main run(args) File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run elastic_launch( File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "/home/cloudam/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent raise ChildFailedError( torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

数据集文件之前在alpaca-lora上可以正常训练

**Comment by Crispy256** [comment]
> 

是的，我删除了这个参数，这个是必须的吗

**Comment by Crispy256** [comment]
> @Crispy256 是不是没提供验证集`--validation_file`?

是的，我删除了这个参数，请问是必须的吗

**Comment by airaria** [comment]
> > @Crispy256 是不是没提供验证集`--validation_file`?
> 
> 是的，我删除了这个参数，请问是必须的吗

是的，目前代码里必须。
所以要么提供一个验证集；要么自行修改代码，把验证集相关逻辑删掉。

**Comment by Crispy256** [comment]
> > > @Crispy256 是不是没提供验证集`--validation_file`?
> > 
> > 
> > 是的，我删除了这个参数，请问是必须的吗
> 
> 是的，目前代码里必须。 所以要么提供一个验证集；要么自行修改代码，把验证集相关逻辑删掉。

感谢， 现在已经正常在跑了

**Comment by ppppls115** [comment]
AttributeError: 'LlamaForCausalLM' object has no attribute 'sava checkpoint'这个报错有遇到过吗，训练一半好像没法保存checkpoint。是不是peft版本的问题
